DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS empRole;
DROP TABLE IF EXISTS department;

CREATE TABLE department (
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(30) NOT NULL
);

CREATE TABLE empRole (
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(30) NOT NULL,   
   department_id INTEGER,
   salary DECIMAL(10,2),
   CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE SET NULL
);

CREATE TABLE employee (
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   first_name VARCHAR(30) NOT NULL,
   last_name VARCHAR(30) NOT NULL,
   role_id INTEGER,
   CONSTRAINT fk_empRole FOREIGN KEY (role_id) REFERENCES empRole(id) ON DELETE SET NULL
)

